name: qr_flutter
description: >
  QR.Flutter is a Flutter library for simple and fast QR code rendering via a
  Widget or custom painter.
version: 3.2.0
homepage: https://github.com/lukef/qr.flutter

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.7.0"

dependencies:
  flutter:
    sdk: flutter
  qr: # ^1.2.0 - TODO: 7a1d3791810050bd1257e70a08ab309b0fa6b996
    git: 
      url: git://github.com/KomodoPlatform/qr.dart.git
      ref: 7a1d3791810050bd1257e70a08ab309b0fa6b996

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.0

flutter:
  uses-material-design: false
